"""empty message

Revision ID: 1d2b9422b4d3
Revises: 868730d741d0
Create Date: 2019-03-25 09:55:34.283620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2b9422b4d3'
down_revision = '868730d741d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.String(length=200), nullable=True, comment='评论id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###
