"""empty message

Revision ID: 7961ef6d4c3f
Revises: 1d2b9422b4d3
Create Date: 2019-04-03 11:28:50.327146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7961ef6d4c3f'
down_revision = '1d2b9422b4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert', sa.Column('Wx', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert', 'Wx')
    # ### end Alembic commands ###
