"""empty message

Revision ID: 868730d741d0
Revises: afc1fb468b99
Create Date: 2019-03-20 17:21:03.805425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868730d741d0'
down_revision = 'afc1fb468b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('question_id', sa.String(length=200), nullable=True, comment='问题id'))
    op.add_column('question', sa.Column('collect_count', sa.Integer(), nullable=True, comment='问题浏览量'))
    op.add_column('user', sa.Column('user_sign', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_sign')
    op.drop_column('question', 'collect_count')
    op.drop_column('comment', 'question_id')
    # ### end Alembic commands ###
