"""empty message

Revision ID: afc1fb468b99
Revises: f2a3fc7200b5
Create Date: 2019-03-20 14:37:21.120511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc1fb468b99'
down_revision = 'f2a3fc7200b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_headImg', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_headImg')
    # ### end Alembic commands ###
