"""empty message

Revision ID: f2a3fc7200b5
Revises: e67c8e4bf184
Create Date: 2019-03-19 10:34:30.301691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a3fc7200b5'
down_revision = 'e67c8e4bf184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert', sa.Column('class_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert', 'class_name')
    # ### end Alembic commands ###
